export const url = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile/:id",
  PROFILES: "/all-profiles",
  ADD_PROFILE: "/add-profile",
  EDIT_PROFILE: "/edit-profile/:id",
  VAT_RETURN: "/vat-returns",
  ADD_PAYE: "/add-paye",
  ALL_PAYE: "/all-paye",
  ADD_EXPENSES: "/add-expenditures",
  ADD_ACCOUNT: "/add-account",
  ACCOUNTS: "/accounts",
  NEW_ASSETS: "/add-assets",
  SETTINGS: "/site-settings",
  INCOME_STATEMENT: "/income-statement",
  BALANCE_SHEET: "/balance-sheet",
  FIXED_ASSETS: "fixed-assets",
  CASH_FLOWS: "cash-flows",
  TRIAL_BALANCE: "trial-balance",
  TAX_COMPUTATION: "tax-computations",
  USER_PROFILE: "/my-profile",
  USER_ACCOUNT: "/my-account",
};
