export const url = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile/:id",
  PROFILES: "/all-profiles",
  ADD_PROFILE: "/add-profile",
  EDIT_PROFILE: "/edit-profile/:pin",
  VAT_RETURN: "/vat-returns",
  ADD_PAYE: "/add-paye",
  ALL_PAYE: "/all-paye",
  EXPENSES: "/expenditure",
  ADD_ACCOUNT: "/add-account",
  ACCOUNTS: "/accounts",
};
